baseURL = "https://jomorespi.github.io/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Jordi Moreno. Blog"
theme = "jordi"
paginate = 8
publishDir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
removePathAccents = true
timeZone = "Europe/Madrid"

[params]
    Description = "Blog personal d'en Jordi Moreno Crespi, desenvolupador web i, a estones, escriptor."
    Author = "Jordi Moreno Crespi"

[permalinks]
    posts = '/entrades/:title'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        hardWraps = true
