name = "Jordi"
license = "MIT"
licenselink = "https://github.com/jomorespi/jomorespi.github.io/blob/master/themes/jordi/LICENSE"
description = "Custom Hugo theme for a personal blog. Based on Blank."
homepage = "https://github.com/jomorespi/jomorespi.github.io/tree/master/themes/jordi/"
demosite = "https://jomorespi.github.io/"
tags = ["blog", "minimal", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Jordi Moreno"
  homepage = "https://jordimoreno.cat"
